server:
  port: 9093
  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
   web:
    exposure:
     include: '*' 
      
spring:
    application:
        name: USER-SERVICE
    datasource:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:C:/Users/2245562/OneDrive - Cognizant/Desktop/Spring/database/sqlite/gui/SQLiteStudio/userdb.sqlite
        password: 
        username: 
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
              dialect: org.hibernate.community.dialect.SQLiteDialect        
        
        
        
    